/// Source map data model for Lost Kingdom BF game.
///
/// Contains reverse-engineered structural information about LostKng.b:
/// regions, sub-regions, notable positions, and string locations.

/// A region of the BF source between input instructions.
#[derive(Clone)]
pub struct Region {
    pub id: usize,
    pub name: &'static str,
    pub raw_start: usize,
    pub raw_end: usize,
    pub bf_ops: usize,
    pub sections: usize,
    pub description: &'static str,
    pub sub_regions: Vec<SubRegion>,
    pub notable: Vec<Notable>,
}

/// A sub-region within a region.
#[derive(Clone)]
pub struct SubRegion {
    pub name: &'static str,
    pub raw_start: usize,
    pub raw_end: usize,
    pub sections: usize,
    pub dots: usize,
    pub description: &'static str,
}

/// A notable code location (action, message, item, room, etc.)
#[derive(Clone)]
pub struct Notable {
    pub category: &'static str,
    pub label: &'static str,
    pub raw_pos: usize,
    pub detail: &'static str,
}

impl Region {
    pub fn size(&self) -> usize {
        self.raw_end - self.raw_start
    }
}

/// Build the complete source map for Lost Kingdom.
pub fn build_source_map() -> Vec<Region> {
    vec![
        Region {
            id: 0,
            name: "Init + Title Screen",
            raw_start: 314,
            raw_end: 25_797,
            bf_ops: 25_134,
            sections: 6,
            description: "Game initialization, title string constants, and opening text.",
            sub_regions: vec![
                SubRegion {
                    name: "Cell init",
                    raw_start: 0,
                    raw_end: 313,
                    sections: 0,
                    dots: 0,
                    description: "Clear cell 0, set cells 0+1 = 1, build constants",
                },
            ],
            notable: vec![],
        },
        Region {
            id: 1,
            name: "Y/N Long Descriptions",
            raw_start: 25_797,
            raw_end: 34_243,
            bf_ops: 8_331,
            sections: 13,
            description: "Prompts for verbose room descriptions (Y/N).",
            sub_regions: vec![],
            notable: vec![],
        },
        Region {
            id: 2,
            name: "Room Display + Look/Inv/Help",
            raw_start: 34_243,
            raw_end: 496_416,
            bf_ops: 455_841,
            sections: 823,
            description: "Largest region. Room descriptions, inventory display, verb dispatch setup.",
            sub_regions: vec![
                SubRegion {
                    name: "Verb dispatch setup",
                    raw_start: 34_243,
                    raw_end: 45_000,
                    sections: 22,
                    dots: 1,
                    description: "Parse input char, set up branch flags",
                },
                SubRegion {
                    name: "Short room descriptions",
                    raw_start: 45_000,
                    raw_end: 156_000,
                    sections: 304,
                    dots: 2_351,
                    description: "20 rooms × (short description + exits)",
                },
                SubRegion {
                    name: "Long room descriptions",
                    raw_start: 156_000,
                    raw_end: 282_000,
                    sections: 211,
                    dots: 5_826,
                    description: "20 rooms × full narrative text",
                },
                SubRegion {
                    name: "Inventory/look display",
                    raw_start: 282_000,
                    raw_end: 375_000,
                    sections: 128,
                    dots: 206,
                    description: "\"You can see:\" / \"You are carrying:\"",
                },
                SubRegion {
                    name: "Floor item descriptions",
                    raw_start: 375_000,
                    raw_end: 416_000,
                    sections: 55,
                    dots: 523,
                    description: "10 items × location descriptions",
                },
                SubRegion {
                    name: "Carried item display",
                    raw_start: 416_000,
                    raw_end: 496_416,
                    sections: 103,
                    dots: 250,
                    description: "Item names with states (lit, full, etc.)",
                },
            ],
            notable: vec![
                Notable { category: "Room", label: "Hut (short)", raw_pos: 45_871, detail: "Short description" },
                Notable { category: "Room", label: "Dirt Path North (short)", raw_pos: 49_036, detail: "Short description" },
                Notable { category: "Room", label: "High Plateau (short)", raw_pos: 52_212, detail: "Short description" },
                Notable { category: "Room", label: "Dirt Path South (short)", raw_pos: 55_900, detail: "Short description" },
                Notable { category: "Room", label: "Forest rooms (short)", raw_pos: 59_152, detail: "4 rooms 59152..69948" },
                Notable { category: "Room", label: "Forest Clearing (short)", raw_pos: 72_519, detail: "Short description" },
                Notable { category: "Room", label: "Dirt Patch/Yard (short)", raw_pos: 76_045, detail: "Short description" },
                Notable { category: "Room", label: "Stagnant Pond (short)", raw_pos: 79_499, detail: "Short description" },
                Notable { category: "Room", label: "Cave Mouth (short)", raw_pos: 82_980, detail: "Short description" },
                Notable { category: "Room", label: "Low Passage (short)", raw_pos: 89_409, detail: "Short description" },
                Notable { category: "Room", label: "Large Cavern (short)", raw_pos: 92_979, detail: "Short description" },
                Notable { category: "Room", label: "Catacombs (short)", raw_pos: 99_290, detail: "8 rooms 99290..127725" },
                Notable { category: "Room", label: "Wall of Flame (short)", raw_pos: 130_812, detail: "Short description" },
                Notable { category: "Room", label: "Junction (short)", raw_pos: 141_873, detail: "Short description" },
                Notable { category: "Room", label: "Church Altar (short)", raw_pos: 145_987, detail: "Short description" },
                Notable { category: "Room", label: "Cave of Gold (short)", raw_pos: 149_981, detail: "Short description" },
                Notable { category: "Room", label: "Dark Cave (short)", raw_pos: 155_640, detail: "Short description" },
                Notable { category: "Room", label: "Hut (long)", raw_pos: 158_898, detail: "Long description" },
                Notable { category: "Room", label: "Dirt Path North (long)", raw_pos: 163_530, detail: "Long description" },
                Notable { category: "Room", label: "High Plateau (long)", raw_pos: 167_610, detail: "Long description" },
                Notable { category: "Room", label: "Dirt Path South (long)", raw_pos: 178_046, detail: "Long description" },
                Notable { category: "Room", label: "Forest rooms (long)", raw_pos: 181_957, detail: "4 rooms 181957..190913" },
                Notable { category: "Room", label: "Forest Clearing (long)", raw_pos: 193_913, detail: "Long description" },
                Notable { category: "Room", label: "Dirt Patch/Yard (long)", raw_pos: 197_463, detail: "Long description" },
                Notable { category: "Room", label: "Stagnant Pond (long)", raw_pos: 201_124, detail: "Long description" },
                Notable { category: "Room", label: "Cave Mouth (long)", raw_pos: 204_892, detail: "Long description" },
                Notable { category: "Room", label: "Low Passage (long)", raw_pos: 211_550, detail: "Long description" },
                Notable { category: "Room", label: "Large Cavern (long)", raw_pos: 215_027, detail: "Long description" },
                Notable { category: "Room", label: "Catacombs (long)", raw_pos: 222_813, detail: "8 rooms 222813..245270" },
                Notable { category: "Room", label: "Wall of Flame (long)", raw_pos: 253_089, detail: "Long description" },
                Notable { category: "Room", label: "Junction (long)", raw_pos: 266_108, detail: "Long description" },
                Notable { category: "Room", label: "Church Altar (long)", raw_pos: 269_828, detail: "Long description" },
                Notable { category: "Room", label: "Cave of Gold (long)", raw_pos: 273_440, detail: "Long description" },
                Notable { category: "Room", label: "Dark Cave (long)", raw_pos: 279_672, detail: "Long description" },
                Notable { category: "Item", label: "Lamp (floor)", raw_pos: 377_929, detail: "rusty old lamp" },
                Notable { category: "Item", label: "Matches (floor)", raw_pos: 381_483, detail: "box of matches" },
                Notable { category: "Item", label: "Dynamite (floor)", raw_pos: 385_055, detail: "stick of dynamite" },
                Notable { category: "Item", label: "Axe (floor)", raw_pos: 388_713, detail: "wooden-handled axe" },
                Notable { category: "Item", label: "Herring (floor)", raw_pos: 392_341, detail: "dead fish / red herring" },
                Notable { category: "Item", label: "Sceptre (floor)", raw_pos: 395_937, detail: "golden sceptre" },
                Notable { category: "Item", label: "Crown (floor)", raw_pos: 399_527, detail: "stolen crown" },
                Notable { category: "Item", label: "Ring (floor)", raw_pos: 403_191, detail: "signet ring" },
                Notable { category: "Item", label: "Scroll (floor)", raw_pos: 406_803, detail: "parchment scroll" },
                Notable { category: "Item", label: "Urn (floor)", raw_pos: 411_231, detail: "wine urn" },
            ],
        },
        Region {
            id: 3,
            name: "Command Argument Input",
            raw_start: 496_416,
            raw_end: 501_564,
            bf_ops: 5_078,
            sections: 8,
            description: "Reads the argument digit for Take/Drop/etc. commands.",
            sub_regions: vec![],
            notable: vec![],
        },
        Region {
            id: 4,
            name: "Movement + Deaths + Help",
            raw_start: 501_564,
            raw_end: 686_477,
            bf_ops: 182_380,
            sections: 154,
            description: "Movement between rooms, death scenarios, and help/info pages.",
            sub_regions: vec![],
            notable: vec![
                Notable { category: "Death", label: "Wildcat eats you", raw_pos: 513_312, detail: "Enter cavern without food" },
                Notable { category: "Death", label: "Village won't help", raw_pos: 517_429, detail: "Go south from junction" },
                Notable { category: "Block", label: "Door impassable", raw_pos: 521_022, detail: "Hut door" },
                Notable { category: "Block", label: "Rock fall impassable", raw_pos: 524_867, detail: "Plateau cave before dynamite" },
                Notable { category: "Death", label: "Fallen off plateau", raw_pos: 543_641, detail: "Wrong direction from plateau" },
                Notable { category: "Death", label: "Pit in dark", raw_pos: 553_729, detail: "Navigate caves without lamp" },
                Notable { category: "Death", label: "Mage kills you", raw_pos: 558_838, detail: "Enter sanctum without axe" },
                Notable { category: "Help", label: "Help text", raw_pos: 565_055, detail: "411 dots" },
                Notable { category: "Help", label: "Further information", raw_pos: 572_442, detail: "935 dots" },
                Notable { category: "Help", label: "Command list", raw_pos: 582_739, detail: "1001 dots" },
                Notable { category: "Help", label: "Parser info", raw_pos: 592_646, detail: "888 dots" },
                Notable { category: "Help", label: "Object manipulation", raw_pos: 602_416, detail: "581 dots" },
                Notable { category: "Help", label: "Classic game nature", raw_pos: 610_569, detail: "808 dots" },
                Notable { category: "Help", label: "Review request", raw_pos: 620_558, detail: "192 dots" },
                Notable { category: "Help", label: "Contact info", raw_pos: 625_896, detail: "216 dots" },
                Notable { category: "Help", label: "Credits", raw_pos: 631_625, detail: "389 dots" },
                Notable { category: "Help", label: "Backstory menu", raw_pos: 649_633, detail: "266 dots" },
                Notable { category: "Help", label: "Chapter I-VI", raw_pos: 656_084, detail: "~6700 dots total (to 719396)" },
            ],
        },
        Region {
            id: 5,
            name: "Item/Combat/Puzzle Actions",
            raw_start: 686_477,
            raw_end: 1_275_890,
            bf_ops: 581_339,
            sections: 607,
            description: "All item interactions, combat, puzzles, and scoring.",
            sub_regions: vec![],
            notable: vec![
                Notable { category: "Score", label: "Score display", raw_pos: 739_749, detail: "\"You scored X points...\"" },
                Notable { category: "Score", label: "Compass found (+5)", raw_pos: 745_748, detail: "" },
                Notable { category: "Score", label: "Fill urn (+5)", raw_pos: 748_648, detail: "" },
                Notable { category: "Score", label: "Fill lamp (+10)", raw_pos: 751_532, detail: "" },
                Notable { category: "Score", label: "Light lamp (+5)", raw_pos: 754_404, detail: "" },
                Notable { category: "Score", label: "Unblock cave (+5)", raw_pos: 757_580, detail: "" },
                Notable { category: "Score", label: "Calm beast (+20)", raw_pos: 760_439, detail: "Hurl herring" },
                Notable { category: "Score", label: "Extinguish fire (+15)", raw_pos: 763_348, detail: "" },
                Notable { category: "Score", label: "Respect gods (+15)", raw_pos: 766_266, detail: "Pray" },
                Notable { category: "Score", label: "Kill mage (+24)", raw_pos: 769_130, detail: "" },
                Notable { category: "Score", label: "Seek approval (+1)", raw_pos: 771_945, detail: "Mutually exclusive with pray" },
                Notable { category: "Death", label: "Match ignites pool", raw_pos: 792_055, detail: "Burn at clearing" },
                Notable { category: "Action", label: "Light lamp (no fuel)", raw_pos: 807_676, detail: "" },
                Notable { category: "Action", label: "Light lamp (lit)", raw_pos: 810_599, detail: "" },
                Notable { category: "Action", label: "Light lamp (success)", raw_pos: 813_513, detail: "+5 pts" },
                Notable { category: "Action", label: "Dynamite clears rubble", raw_pos: 848_361, detail: "+5 pts" },
                Notable { category: "Action", label: "Dynamite wind blows out", raw_pos: 855_939, detail: "" },
                Notable { category: "Action", label: "Match watch burn", raw_pos: 873_873, detail: "" },
                Notable { category: "Action", label: "Burn: bad idea", raw_pos: 886_226, detail: "" },
                Notable { category: "Action", label: "Burn scroll (destroy ID)", raw_pos: 893_593, detail: "" },
                Notable { category: "Death", label: "Drink pond water", raw_pos: 934_449, detail: "Poison" },
                Notable { category: "Death", label: "Drink crude oil", raw_pos: 947_858, detail: "Poison" },
                Notable { category: "Death", label: "Drink burning oil", raw_pos: 956_145, detail: "" },
                Notable { category: "Death", label: "Drink rotten fish", raw_pos: 967_580, detail: "Poison" },
                Notable { category: "Action", label: "Hurl urn at fire", raw_pos: 1_001_145, detail: "+15 pts" },
                Notable { category: "Action", label: "Hurl herring in dark", raw_pos: 1_009_934, detail: "+20 pts" },
                Notable { category: "Death", label: "Lamp ignites pool", raw_pos: 1_062_393, detail: "Drop lamp at pool" },
                Notable { category: "Death", label: "Drop herring near wildcat", raw_pos: 1_106_085, detail: "" },
                Notable { category: "Action", label: "Fill lamp", raw_pos: 1_134_970, detail: "+10 pts" },
                Notable { category: "Action", label: "Fill urn", raw_pos: 1_160_916, detail: "+5 pts" },
                Notable { category: "Action", label: "Kill mage", raw_pos: 1_190_600, detail: "+24 pts" },
                Notable { category: "Action", label: "Pray: gods pleased", raw_pos: 1_230_306, detail: "+15 pts" },
                Notable { category: "Action", label: "Pray: powerful force", raw_pos: 1_234_311, detail: "+1 pt" },
                Notable { category: "Action", label: "Pray: no help here", raw_pos: 1_254_969, detail: "" },
            ],
        },
        Region {
            id: 6,
            name: "Quit Confirmation",
            raw_start: 1_275_890,
            raw_end: 1_291_268,
            bf_ops: 15_167,
            sections: 12,
            description: "Handles quit command confirmation (Y/N).",
            sub_regions: vec![],
            notable: vec![],
        },
        Region {
            id: 7,
            name: "Save/Restore + Score + Read/Take",
            raw_start: 1_291_268,
            raw_end: 2_113_325,
            bf_ops: 810_796,
            sections: 311,
            description: "Save/restore game state, read/take items, score reporting, win condition.",
            sub_regions: vec![
                SubRegion {
                    name: "Read item text",
                    raw_start: 1_320_270,
                    raw_end: 1_376_410,
                    sections: 20,
                    dots: 500,
                    description: "Text for reading matches, compass, dynamite, ring, scroll, urn",
                },
                SubRegion {
                    name: "Take/inventory",
                    raw_start: 1_376_410,
                    raw_end: 1_497_452,
                    sections: 30,
                    dots: 300,
                    description: "Take item handling, 'already holding', 'too many items', inventory names",
                },
                SubRegion {
                    name: "RESTORE game",
                    raw_start: 1_497_452,
                    raw_end: 1_763_876,
                    sections: 626,
                    dots: 0,
                    description: "Deserialize ~300 cells of game state from save format",
                },
                SubRegion {
                    name: "STORE game",
                    raw_start: 1_772_630,
                    raw_end: 1_985_130,
                    sections: 634,
                    dots: 0,
                    description: "Serialize ~300 cells of game state to save format",
                },
            ],
            notable: vec![
                Notable { category: "Read", label: "Read matches", raw_pos: 1_320_270, detail: "" },
                Notable { category: "Read", label: "Read compass", raw_pos: 1_326_980, detail: "" },
                Notable { category: "Read", label: "Read dynamite", raw_pos: 1_330_442, detail: "" },
                Notable { category: "Read", label: "Read ring", raw_pos: 1_340_980, detail: "" },
                Notable { category: "Read", label: "Read scroll", raw_pos: 1_346_808, detail: "" },
                Notable { category: "Read", label: "Read urn", raw_pos: 1_352_656, detail: "" },
                Notable { category: "Error", label: "Already holding", raw_pos: 1_376_410, detail: "" },
                Notable { category: "Error", label: "Too many items", raw_pos: 1_384_068, detail: "" },
                Notable { category: "Action", label: "Inventory item names", raw_pos: 1_425_494, detail: "" },
                Notable { category: "Win", label: "Reclaimed birthright", raw_pos: 1_994_430, detail: "" },
                Notable { category: "Error", label: "Didn't understand", raw_pos: 2_000_535, detail: "" },
                Notable { category: "Error", label: "Can't go that way", raw_pos: 2_004_838, detail: "" },
                Notable { category: "Error", label: "Specify item", raw_pos: 2_012_422, detail: "" },
                Notable { category: "Error", label: "No such item", raw_pos: 2_016_452, detail: "" },
                Notable { category: "Score", label: "Score notification", raw_pos: 2_021_994, detail: "" },
            ],
        },
        Region {
            id: 8,
            name: "Another Game? + End-of-Turn",
            raw_start: 2_113_325,
            raw_end: 2_133_142,
            bf_ops: 19_546,
            sections: 12,
            description: "Death header, score summary, rank display, play again prompt.",
            sub_regions: vec![],
            notable: vec![
                Notable { category: "UI", label: "Death header", raw_pos: 2_030_743, detail: "" },
                Notable { category: "UI", label: "Score summary + rank", raw_pos: 2_047_086, detail: "" },
                Notable { category: "Rank", label: "Adventurer (0-14)", raw_pos: 2_061_933, detail: "" },
                Notable { category: "Rank", label: "Experienced (15-29)", raw_pos: 2_067_727, detail: "" },
                Notable { category: "Rank", label: "Seasoned (30-44)", raw_pos: 2_073_605, detail: "" },
                Notable { category: "Rank", label: "Junior Master (45-59)", raw_pos: 2_079_503, detail: "" },
                Notable { category: "Rank", label: "Master 2nd Class (60-74)", raw_pos: 2_085_389, detail: "" },
                Notable { category: "Rank", label: "Master 1st Class (75-89)", raw_pos: 2_091_334, detail: "" },
                Notable { category: "Rank", label: "Grandmaster (90-100)", raw_pos: 2_097_194, detail: "" },
                Notable { category: "UI", label: "Another game? (Y/N)", raw_pos: 2_113_109, detail: "" },
            ],
        },
        Region {
            id: 9,
            name: "Easter Egg + Final Loop",
            raw_start: 2_133_142,
            raw_end: 2_159_824,
            bf_ops: 26_316,
            sections: 22,
            description: "Easter egg message, solution records, 'Thanks for playing.'",
            sub_regions: vec![],
            notable: vec![
                Notable { category: "Easter", label: "Easter egg message", raw_pos: 2_144_469, detail: "" },
                Notable { category: "Easter", label: "Shortest solution (84 moves)", raw_pos: 2_146_496, detail: "Daniel B Cristofani" },
                Notable { category: "Easter", label: "Author's solution record", raw_pos: 2_152_632, detail: "" },
                Notable { category: "UI", label: "Thanks for playing", raw_pos: 2_159_560, detail: "" },
            ],
        },
    ]
}
